### PR TITLE
feat: add the ability to call transaction instance methods separately

### PR DESCRIPTION
**Pull request by niusia-ua**
Hello. I recently decided to use your library in my project. However, I ran into the problem that it cannot be used in any other way than through a chaining. This seems to me to be a serious problem, so I decided to solve it.

Please review my changes.

P.S. I have solved this problem, but to call the methods separately, you need to call `.clone()` first. I think it's not a big deal, but I don't know how to get rid of this annoying call.

### CODE REVIEW

**Comment by MovAh13h** [comment]
Hi @niusia-ua, do you mind explaining what you mean by the library only having one way of being used. From what I understand, you would like to call individual methods.

Here is an example where you can use single operations like transactions:

```rs
use std::io;
use tfio::{CopyFile, RollbackableOperation};

fn main() -> io::Result<()> {
	let mut copy_operation = CopyFile::new("./foo.txt", "./bar/baz/foo.txt");
	
	// Execute the operation
	if let Err(e) = copy_operation.execute() {
		eprintln!("Error during execution: {}", e);
		
		// Rollback the operation
		if let Err(ee) = copy_operation.rollback() {
			panic!("Error during rollback: {}", ee);
		}
	}
	Ok(())
}
```
The above example only shows `CopyFile` but every operation provided by the library can be imported and used just like a transaction ie. with `execute` and `rollback`.  A `tfio::Transaction` is just a helper for chaining in case you have several sequential IO tasks.

Also, adding `Clone` to every operation is not ideal because some of the operations have an underlying buffer. As you can see from the source code [here](https://doc.rust-lang.org/src/alloc/vec/mod.rs.html#2722), calling `clone` on vector returns a copy of the entire buffer and not just work with references.

**Comment by niusia-ua** [comment]
Hello. Thank you for your quick response.
I mean, it would be great to add the ability to call methods on the transaction instance separately, not just in the chain.

```rust
let tr = Transaction::new();
tr.op1();
tr.op2();
// etc.
```

Currently, you can't do this because of some errors related to instance capture (I can't remember the exact wording without the compiler 😅).

My use case for your library is that I need to pass a reference of a transaction instance to a function that recursively performs certain manipulations with the file system. Accordingly, in the place where I call this function, I want to set up a single error handling so that I can roll back all changes in case of any problems.

As for my changes, it was just a quick decision that came to my mind. I apologize for being so brash. I probably should have created an issue first.

**Comment by MovAh13h** [comment]
No worries. Let me see what I can do. I haven't tested it in the way you mention it but let me see if I can push a fix and a new release in a day or two.

**Comment by niusia-ua** [comment]
Hello. Thank you for your quick response. I mean, it would be great to add the ability to call methods on the transaction instance.

```rust
let tr = Transaction::new();
tr.op1();
tr.op2();
// etc.
```

Currently, you can't do this because of some errors related to instance capture (I can't remember the exact wording without the compiler 😅).

My use case for your library is that I need to pass a reference to a transaction instance to a function that recursively performs certain manipulations with the file system. Accordingly, in the place where I call this function, I want to set up a single error handling so that I can roll back all changes in case of any problems.

As for my changes, it was just a quick decision that came to my mind. I apologize for being so brash. I probably should have created an issue first.

**Comment by MovAh13h** [comment]
I have the fix for this situation but there are more problems (not related to the recursive use of `Transaction`) that I need to address. There is inconsistency in the code and sometimes the created files/directories are not deleted correctly.


I will try to do a rewrite and get a proper release going by next weekend.

**Comment by niusia-ua** [comment]
Yes, I have also encountered that some directories and files are not deleted correctly. In general, these are the bar directory and PATH_TO_TEMP_DIR, because they are created via std::fs in doctests. Although in normal tests some directories are not deleted even if they were created in a transaction, I did not deal with this.

**Comment by niusia-ua** [comment]
As for your changes, everything is great. I'm all for you improving the library even more.

**Comment by MovAh13h** [comment]
> Yes, I have also encountered that some directories and files are not deleted correctly. In general, these are the bar directory and PATH_TO_TEMP_DIR, because they are created via std::fs in doctests. Although in normal tests some directories are not deleted even if they were created in a transaction, I did not deal with this.

Yes I noticed this. I will be fixing all these small issues this week so we can have tfio v2.0.0

**Comment by niusia-ua** [comment]
That's great. Will you skip version 1.0.0?)

**Comment by niusia-ua** [comment]
By the way, have you considered making the names of your library's structures and methods closer to std::fs? That is, instead of "delete" use "remove" and so on?

**Pull request closed without merging**
